#!/usr/bin/env rake
# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require File.expand_path('../config/application', __FILE__)

Rails.application.load_tasks
namespace :db do
  namespace :test do
    task prepare: :environment do
      system("bundle exec rake db:reset RAILS_ENV=test")
    end
  end
end